services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_USER_SERVICE_API: localhost:3000
        VITE_QUESTION_SERVICE_API: localhost:3001
        VITE_MATCHING_SERVICE_API: localhost:3003
        VITE_COLLABORATION_SERVICE_API: localhost:1234
        VITE_CHAT_SERVICE_API: localhost:3004
        VITE_SUBMISSION_SERVICE_API: localhost:3005
        VITE_GOOGLE_AI_API_KEY: AQ.Ab8RN6L_lIqX16q2by-E35pHoEkURM9WYw1n8wWNjvu7ILtCEg
    ports:
      - "5173:5173"

  user-service:
    build: ./backend/user_service
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: peerprep_user_service
      REDIS_URL: redis://redis:6379/1
      JWT_SECRET_KEY: secret
      GMAIL: peerprepg04@gmail.com
      GMAIL_APP_PASSWORD: uqvu qfwl tmeq rimg
      WEBSITE_URL: http://localhost:5173
    depends_on:
      postgres:
        condition: service_healthy

  question-service:
    build: ./backend/question_service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: peerprep_question_service
      REDIS_URL: redis://redis:6379/1
      JWT_SECRET_KEY: secret
    depends_on:
      postgres:
        condition: service_healthy

  matching-service:
    build: ./backend/matching_service
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: peerprep_matching_service
      JWT_SECRET_KEY: secret
      REDIS_URL: redis://redis:6379/0
      QUESTION_SERVICE_URL: http://question-service:3001
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  collaboration-service:
    build: ./backend/collaboration_service
    ports:
      - "1234:1234"
    environment:
      PORT: 1234
      JWT_SECRET_KEY: secret
      REDIS_URL: redis://redis:6379
    depends_on:
      redis:
        condition: service_started

  chat-service:
    build: ./backend/chat_service
    ports:
      - "3004:3004"
    environment:
      PORT: 3004
      JWT_SECRET_KEY: secret

  submission-service:
    build: ./backend/submission_service
    ports:
      - "3005:3005"
    environment:
      PORT: 3005
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: peerprep_submission_service
      JWT_SECRET_KEY: secret
      MATCHING_SERVICE_URL: http://matching-service:3003

  postgres:
    image: postgres:18
    container_name: app-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./database-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8
    ports:
      - "6379:6379"

volumes:
  pgdata:
